### ISSUE TITLE
Installation documentation needs rework

### ISSUE THREAD

**Issue by Wieb1960** [ibm-messaging/mq-trigger-monitor-windows#1]
The readme.odt in /src needs a rework. 
If installing with a different windows service name using the file "servicename", this file needs to be in the same directory as "setup.exe". 
Setup.exe is in /bin, so file "servicename" needs to be moved from /src to /bin before strating the setup procedure.

**Comment by jefflowrey** [comment]
Hi -
Thanks for your comment!  I agree.  I've copied the servicename file into the bin directory.  

And I've updated the docs to indicate a couple of options.
